apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_IcUyqOFG5L9Y@ep-curly-band-a18n7kol-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  BETTER_AUTH_SECRET: "local_dev_secret_12345678901234567890123456789012"
  OPENAI_API_KEY: "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"
