# src/services/task_manager.py
from src.models.task import Task
from src.services.task_storage import TaskStorage

class TaskManager:
    def __init__(self, task_storage: TaskStorage):
        self._task_storage = task_storage

    def add_task(self, title: str, description: str = "") -> Task:
        # Task ID will be generated by TaskStorage
        new_task = Task(id=None, title=title, description=description, status="pending")
        self._task_storage.add_task(new_task)
        return new_task

    def get_task(self, task_id: str) -> Task:
        return self._task_storage.get_task(task_id)

    def get_all_tasks(self) -> list[Task]:
        return self._task_storage.get_all_tasks()

    def update_task(self, task_id: str, title: str = None, description: str = None, status: str = None) -> Task:
        task = self._task_storage.get_task(task_id)
        if not task:
            raise ValueError(f"Task with ID {task_id} not found.")
        if title is not None:
            task.title = title
        if description is not None:
            task.description = description
        if status is not None:
            task.status = status
        self._task_storage.update_task(task)
        return task

    def toggle_task_status(self, task_id: str) -> Task:
        task = self._task_storage.get_task(task_id)
        if not task:
            raise ValueError(f"Task with ID {task_id} not found.")
        task.status = "completed" if task.status == "pending" else "pending"
        self._task_storage.update_task(task)
        return task

    def delete_task(self, task_id: str) -> None:
        self._task_storage.delete_task(task_id)