apiVersion: v1 
kind: Service 
metadata: 
  name: redpanda 
  namespace: redpanda 
spec: 
  clusterIP: None 
  selector: 
    app: redpanda 
  ports: 
  - name: kafka 
    port: 9092 
--- 
apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: redpanda 
  namespace: redpanda 
spec: 
  serviceName: redpanda 
  replicas: 1 
  selector: 
    matchLabels: 
      app: redpanda 
  template: 
    metadata: 
      labels: 
        app: redpanda 
    spec: 
      containers: 
      - name: redpanda 
        image: docker.redpanda.com/redpandadata/redpanda:latest 
        command: 
        - /bin/bash 
        - -c 
        - "redpanda start --mode dev-container --smp 1 --overprovisioned" 
        ports: 
        - containerPort: 9092 
