apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "d647u43t489913vp2r0g.any.us-east-1.mpx.prd.cloud.redpanda.com:9092"
  - name: authType
    value: "password"
  - name: saslMechanism
    value: "SCRAM-SHA-256"
  - name: saslUsername
    secretKeyRef:
      name: kafka-secrets
      key: user
  - name: saslPassword
    secretKeyRef:
      name: kafka-secrets
      key: password
  - name: consumerID
    value: "todo-app-cloud-group"
  - name: disableTls
    value: "false"
  - name: deadLetterTopic
    value: "dead-letters"