apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "PLACEHOLDER_REDPANDA_BOOTSTRAP_URL:9092"
  - name: authType
    value: "sasl_scram_sha256"
  - name: saslUsername
    secretKeyRef:
      name: kafka-secrets
      key: username
  - name: saslPassword
    secretKeyRef:
      name: kafka-secrets
      key: password
  - name: consumerID
    value: "todo-app-cloud-group"
  - name: disableTls
    value: "false"
  - name: deadLetterTopic
    value: "dead-letters"
